### ISSUE TITLE
An issue

### ISSUE THREAD

**Issue by mike-north** [Eli415/max#1]
This should result in you getting a notification if you're "Watching" this repo

**Comment by mike-north** [comment]
@Eli415 I'm mentioning you so you get another notification

**Comment by Eli415** [comment]
thanks for these comments and the PR.

so, these watching options aren't very granular. good to see:
![image](https://user-images.githubusercontent.com/456839/90074703-9b88a580-dcb0-11ea-8d04-671cc2b88a2b.png)
